# This is a hands-on task to create the cloudformation stack with
# 2 EC2 instances in total & one s3 bucket
# Webserver with 8gb EBS
# Appserver with 10gb EBS
# One S3 bucket to store invoice pdf files



Parameters: # --The parameter section is used to avoid hardcoding and to make the template [Dynamic]. [Indent [here] before starting next line]
  EC2InstanceType: # --Enter [LogicalName] This InstanceType will be Ref in the resource section. [Indent [here] before starting next line]
    Type: "String" # --This parameter type is a string. [Type, Default, and Description are in the same line]
    Default: "t2.micro" # --The default is used to assigned one specific instancetype to be use by the resource.
    Description: "put required ec2 instance type, default is t2.micro" # --This is to desribe what the parameter about
  ImageId: # --To start another parameter, go back to the line where the first parameter line is. --Enter [LogicalName] for the next paramter
    Description: The EC2 AMI id # --This is to desribe what the parameter about
    Type: String  # --This parameter type is a string. [Type, Default, and Description are in the same line]
    Default: ami-0022f774911c1d690 # --The default is used to assigned one specific instancetype to be use by the resource.
    ConstraintDescription: Must be a valid AMI based on the region.   # --A string that explains a constraint when the constraint is violated.


Resources:  # --The Resource section is manditory for a template to be valid. Indent once, then enter [logicalName --WebServer].
  WebServer:   #-- this part is for the logicalName. Indent once, then enter [Type:].
    Type: AWS::EC2::Instance # --This section tells you what type of resource that is being created.
    Properties:   # --Everything that the resource need to operate is under the property section
      ImageId: !Ref ImageId # --The ImageId here is being Ref from the parameter section.
      InstanceType: !Ref EC2InstanceType  # --The InstanceType here is being Ref from the parameter section.
      KeyName: "commands"  #--Putting keypair here makes this part of the template haedcoded and you must use a keypair from us-east-1
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm" #--This is mounting port for which to attach your EBS volume
        Ebs:
          VolumeType: "io1" # --This part tells you what volumetype you are using
          Iops: 100  # -- IOP is an integer
          DeleteOnTermination: true  #--This is a Boolean
          VolumeSize: 8  # ---This is an integer
  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref EC2InstanceType
      KeyName: "commands"
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: true
          VolumeSize: 10
  InvoiceS3Bucket:  #-- this part is for the logicalName for the s3 bucket. Indent once, then enter [Type:].
    Type: AWS::S3::Bucket  # --This section tells you what type of resource that is being created.
    Properties:  # --Everything that the resource need to operate is under the property section
      AccessControl: "PublicRead" # --The bucket is made public by this policy.
