# In this template we are going to learn about outputs
# Use of outputs, exports
# !GetAtt intrinsic function
# Ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html

---
AWSTemplateFormatVersion: '2010-09-09'  # --This tells you the template version
Description: 'Cloudformation template to create Security group and making it as output' # --This is to desribe what the template is about
Parameters:  # --The parameter section is used to avoid hardcoding and to make the template [Dynamic]. [Indent [here] before starting next line]
  SecurityGroupPorts: # --Enter [LogicalName] This InstanceType will be Ref in the resource section. [Indent [here] before starting next line]
    Description: Simple Description of a Number Parameter, with MinValue and MaxValue # --This is to desribe what the parameter about
    Type: Number  # --This parameter type is an integer. [Type, AllowedValue, and Description are in the same line]
    AllowedValues: # --Allowed value is used to define what types of properties[instancetypes] that ia allowed be use.
      - 80  # --These are the allowed values to choose from when creating the the Server
      - 443
      - 22
          # ---The use of Constraint is optional

  SSHLocation:  # --Enter [LogicalName] This InstanceType will be Ref in the resource section. [Indent [here] before starting next line]
    Description: The IP address range that can be used to SSH to the EC2 instances # --This is to desribe what the parameter about
    Type: String  # --This parameter type is a string. [Type, Default, and Description are in the same line]
    MinLength: '9'  # --The default is used to assigned one specific instancetype to be use by the resource.
    MaxLength: '18'  # --Using MixValue allows you to defined the miximum size of volume that the user can use
    Default: 0.0.0.0/0  # --The default is used to assigned one specific instancetype to be use by the resource.
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})" # --AllowedPattern is used to define what types of pattern that is allowed.
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.  # --And the Constraint is use to describe the rules.

Resources:  # --The Resource section is manditory for a template to be valid. Indent once, then enter [logicalName --WebServer].
  InstanceSecurityGroup:    #-- this part is for the logicalName. Indent once, then enter [Type:].
    Type: AWS::EC2::SecurityGroup  # --This section tells you what type of resource that is being created.
    Properties:   # --Everything that the resource need to operate is under the property section
      GroupDescription: Enable SSH access via port 22  # --This section tells you what type of resource that is being created.
      SecurityGroupIngress:  # --Ingress is used to Add an inbound rule to a security group.
      - IpProtocol: tcp  # --The IP protocol name (tcp, udp, icmp, icmpv6)
        FromPort: !Ref SecurityGroupPorts  # --The FromPort here is being Ref from the parameter section. [The start of port range for the TCP] [1]
        ToPort: !Ref SecurityGroupPorts # --The ToPort here is being Ref from the parameter section. [The end of port range for the TCP]. [2]
        CidrIp:
          Ref: SSHLocation # --The CidrIP here is being Ref from the parameter section. [3]

Outputs: # --The optional Outputs section declares output values that you can import into other stacks (to create cross-stack references)
  SecurityGroupId:  #-- this part is for the logicalName. Indent once, then enter [Description].
    Description: Get the GoupId of the Newly created SecurityGroup  # --This is to desribe what the parameter about
    Value: !GetAtt # --Value is use for Referencing a value from the resource section.
    # --The Fn::GetAtt intrinsic function returns the value of an attribute from a resource in the template.
    # --The first part is for the [LogicalName of the resource] and
    # --the second part is the [Attribute, which is the ReturnValue you want to get] [GroupId] or [VpcId]
      - InstanceSecurityGroup # --The first part is for the [LogicalName of the resource]
      - GroupId  # --the second part is the [Attribute, which is the ReturnValue you want to get] [GroupId] or [VpcId]
    Export:  # --The name of the resource output to be exported for a cross-stack reference.
      Name: WebSeverSecurityGroupId  # --The Export Name is what CFN will use to find the logicalName and the attribute value.
      # --exported name have to be unique within your acount and region. you cannot export the same name multiple times.
  VpcId:   #-- this part is for the logicalName. Indent once, then enter [Description].
    Description: VPC id to which the Security group belongs too. # --This is to desribe what the parameter about
    Value: !GetAtt   # --Value is use for Referencing a value from the resource section.
    # --The Fn::GetAtt intrinsic function returns the value of an attribute from a resource in the template.
    # --The first part is for the [LogicalName of the resource] and
    # --the second part is the [Attribute, which is the ReturnValue you want to get] [GroupId] or [VpcId]
      - InstanceSecurityGroup  # --The first part is for the [LogicalName of the resource] and
      - VpcId   # --the second part is the [Attribute, which is the ReturnValue you want to get] [GroupId] or [VpcId]
